# .github/workflows/ci-unit.yml
name: CI - unit tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: pip
          cache-dependency-path: |
            requirements.txt
            pyproject.toml
      - name: Install dev deps via Makefile
        run: make install-dev
      - name: Unit tests
        run: make test_unit
      - name: Bootstrap pytest for unit tests
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r tests/requirements.txt
      - name: Dev setup (optional)
        run: make install-dev
      - name: Unit tests (pytest)
        run: make test_unit
