# .github/workflows/ci.yml
name: lint-and-test
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  python:
    runs-on: ubuntu-latest
    strategy:
      matrix: { python-version: ['3.12'] }
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install ruff mypy pytest
      - name: Ruff (lint)
        run: ruff check .
      - name: Ruff (format check)
        run: ruff format --check .
      - name: Type-check (mypy)
        run: mypy --ignore-missing-imports .
      - name: Tests
        env:
          PYTHONPATH: .
        run: python -m pytest -q

name: CI - unit tests
on: [push, pull_request]
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: make install-dev
      - run: make test_unit
