name: ci

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt
            pyproject.toml

      - name: Install dev deps via Makefile
        run: make install-dev

      - name: Ruff (lint)
        run: make lint

      - name: Ruff (format check)
        run: make format-check

      - name: Type-check (mypy)
        run: make typecheck

  unit-tests:
    runs-on: ubuntu-latest
    needs: lint-and-typecheck   # optional; remove if you want parallel jobs
    env:
      QT_QPA_PLATFORM: offscreen
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt
            pyproject.toml

      # Qt headless deps (+ fonts to silence QFontDatabase warnings)
      - name: System deps for Qt headless
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libegl1 libgl1 libxkbcommon-x11-0 libxcb-xinerama0 libxcb-randr0 \
            libxcb-image0 libxcb-util1 libxcb-keysyms1 xvfb fonts-dejavu-core

      - name: Install dev deps via Makefile
        run: make install-dev

      - name: Run unit tests (headless)
        run: xvfb-run -a make test_unit
