name: release-on-tag
on:
  push:
    tags: [ "v*" ]
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to build & release (e.g., v0.1.0)"
        required: true

permissions:
  contents: write   # allow creating GitHub Releases

jobs:
  build-release:
    runs-on: windows-latest
    steps:
      # Checkout the exact tag when run manually; otherwise use the pushed tag
      - name: Checkout (manual run)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/checkout@v4
        with:
          ref: refs/tags/${{ inputs.tag }}

      - name: Checkout (on tag push)
        if: ${{ github.event_name == 'push' }}
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install build deps
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with PyInstaller
        shell: pwsh
        run: pyinstaller .\DesktopTileLauncher.spec

      - name: Create GitHub Release and upload EXE
        uses: softprops/action-gh-release@v2
        with:
          # when manual, use the input; on tag push, github.ref_name is the tag
          tag_name: ${{ github.event_name == 'workflow_dispatch' && inputs.tag || github.ref_name }}
          generate_release_notes: true
          files: dist/**/DesktopTileLauncher.exe
