# .github/workflows/security-audit.yml
name: security-audit
on:
  workflow_dispatch:
  schedule: [ { cron: '0 4 * * 1' } ]
jobs:
  pip-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with: { python-version: '3.12', cache: 'pip' }
      - run: pip install -r requirements.txt
      - run: pip install pip-audit bandit
      - name: pip-audit
        run: pip-audit -l
      - name: Bandit
        run: bandit -r .
